title: "Yann Loscos"
description: "Game Programmer • C++ • Unreal Engine"
theme: null

markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Empêche Jekyll d’ajouter la sidebar du thème
layout: default

# Ajout d’un style CSS minimaliste
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
